const VAR_ACCURACY = 5
const VAR_GRAVITY = 400
const VAR_CLOTH_WIDTH = 54;
const VAR_CLOTH_HEIGHT = 28;
const VAR_SPACING = 15
const VAR_TEARDISTANCE = 60
const VAR_FRICTION = 0.99
const VAR_BOUNCE = 0.5